#!/bin/bash

export TOOLS_PATH=PATH_FOR_DSBULK_AND_CQLSH

export CQLSH_BIN_PATH=$TOOLS_PATH/cqlsh-astra/bin
export DSBULK_BIN_PATH=$TOOLS_PATH/dsbulk-1.8.0/bin
export USER_NAME=YOUR_CLIENT_ID
export PASSWORD=YOUR_CLIENT_SECRETE
export PATH_TO_BUNDLE=PATH_TO_YOUR_SECURE_BUNDLE

